### ISSUE TITLE
你好，请问懂球帝的API在哪找的？

### ISSUE THREAD

**Issue by hezhongfeng** [vqlai/vue2-football#2]
RT~

**Comment by vqlai** [comment]
你可以打开懂球帝官网即http://m.dongqiudi.com，然后按f12打开开发者工具，选择network->XHR，即可找到懂球帝每个页面的请求路径与参数了

**Comment by hezhongfeng** [comment]
这样啊
谢谢，我以为有专门的api说明呢，哈哈
